---

- name: create temp dir
  tempfile:
    suffix: .molecule
    state: directory
  register: _molecule_docker_build_dir
  when: lookup('env', 'ANSIBLE_MOLECULE_DOCKER_BUILD_DIR') is not defined

- name: ANSIBLE_MOLECULE_DOCKER_BUILD_DIR
  debug: msg="{{ lookup('env', 'ANSIBLE_MOLECULE_DOCKER_BUILD_DIR')|default(_molecule_docker_build_dir.path) }}"
  tags:
    - debug

- name: Dockerfile etc. is present
  copy:
    src: src/
    dest: "{{ lookup('env', 'ANSIBLE_MOLECULE_DOCKER_BUILD_DIR')|default(_molecule_docker_build_dir.path) }}"

- name: packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-docker-py
    - docker-client

- name: docker image is built
  docker_image:
    path: "{{ lookup('env', 'ANSIBLE_MOLECULE_DOCKER_BUILD_DIR')|default(_molecule_docker_build_dir.path) }}"
    name: molecule
    tag: v2
    state: present
